In [1]:
import torch

In [2]:
a = torch.tensor([5.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [3]:
a

tensor([5.], requires_grad=True)

In [4]:
b

tensor([6.], requires_grad=True)

In [5]:
y = a**3 - b**2

In [6]:
y

tensor([89.], grad_fn=<SubBackward0>)

In [8]:
print(a.grad)

None


In [9]:
y.backward()

In [10]:
a.grad

tensor([75.])

In [11]:
b.grad

tensor([-12.])

In [13]:
W = torch.randn(10, 1, requires_grad = True)
b = torch.randn( 1, requires_grad = True)

In [14]:
W

tensor([[ 0.5584],
        [-0.7711],
        [-0.1811],
        [ 0.3154],
        [ 1.2575],
        [ 0.3503],
        [-0.7236],
        [-1.0527],
        [ 0.8261],
        [-0.6778]], requires_grad=True)

In [15]:
X = torch.rand(1, 10)

In [17]:
X

tensor([[0.4578, 0.1978, 0.3106, 0.7069, 0.5582, 0.8155, 0.0636, 0.3721, 0.4704,
         0.9195]])

In [20]:
output = torch.matmul(X,W)+ b

In [21]:
loss = 1- output

In [22]:
loss

tensor([[-1.0325]], grad_fn=<RsubBackward1>)

In [23]:
output

tensor([[2.0325]], grad_fn=<AddBackward0>)

In [31]:
loss.backward()


RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.

In [28]:
with torch.no_grad():
    W  = W - .001 * W.grad.data
    

AttributeError: 'NoneType' object has no attribute 'data'